name: Deploy Specific Lambda

on:
  workflow_dispatch:
    inputs:
      lambda_function:
        description: "Name of the Lambda function to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Verify compiled files exist
        run: ls -lR dist/functions

      - name: Zip the Lambda function
        run: |
          cd dist/functions/${{ github.event.inputs.lambda_function }}
          zip -r ../../../${{ github.event.inputs.lambda_function }}.zip .
          cd ../../../

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1 # Change to your AWS region

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ${{ github.event.inputs.lambda_function }} --zip-file fileb://${{ github.event.inputs.lambda_function }}.zip
